# faça uma tabuada com os operadores aritmeticos sem loops

tab = int(input('Digite um numero: '))
print('-' * 20)
print('a tabuada do {} é: '.format(tab))
print('{} * {:2} = {}'.format(tab, 1, tab * 1))
print('{} * {:2} = {}'.format(tab, 2, tab * 2))
print('{} * {:2} = {}'.format(tab, 3, tab * 3))
print('{} * {:2} = {}'.format(tab, 4, tab * 4))
print('{} * {:2} = {}'.format(tab, 5, tab * 5))
print('{} * {:2} = {}'.format(tab, 6, tab * 6))
print('{} * {:2} = {}'.format(tab, 7, tab * 7))
print('{} * {:2} = {}'.format(tab, 8, tab * 8))
print('{} * {:2} = {}'.format(tab, 9, tab * 9))
print('{} * {:2} = {}'.format(tab, 10,tab * 10))
print('-' * 20)